export let storeproducts = [{
        id: "1",
        name: "The Cinema",
        description: "Top quality snowboard produced in the Norwegian mountains, the perfect place for them.",
        price: "4 499",
        image: "./products/product_images/snowboards/snowboard_the_cinema.jpg",
        type: "Snowboard",
        popularity: "0",
    },
    {
        id: "2",
        name: "Explosive Energy",
        description: "Top quality snowboard produced in the Norwegian mountains, the perfect place for them.",
        price: "4 799",
        image: "./products/product_images/snowboards/snowboard_explosive_energy.jpg",
        type: "Snowboard",
        popularity: "1",
    },
    {
        id: "3",
        name: "Lightning rod",
        description: "Top quality snowboard produced in the Norwegian mountains, the perfect place for them.",
        price: "5 149",
        image: "./products/product_images/snowboards/snowboard_Lightning_rod.jpg",
        type: "Snowboard",
        popularity: "3",
    },
    {
        id: "4",
        name: "Mountain Lion",
        description: "Top quality snowboard produced in the Norwegian mountains, the perfect place for them.",
        price: "3 799",
        image: "./products/product_images/snowboards/snowboard_mountain_lion.jpg",
        type: "Snowboard",
        popularity: "2",
    },
    {
        id: "5",
        name: "Mountain Rider",
        description: "Top quality snowboard produced in the Norwegian mountains, the perfect place for them.",
        price: "4 999",
        image: "./products/product_images/snowboards/snowboard_mountain_rider.jpg",
        type: "Snowboard",
        popularity: "6",
    },
    {
        id: "6",
        name: "The Airbourne",
        description: "Top quality snowboard produced in the Norwegian mountains, the perfect place for them.",
        price: "6 199",
        image: "./products/product_images/snowboards/snowboard_the_airbourne.jpg",
        type: "Snowboard",
        popularity: "5",
    },
    {
        id: "7",
        name: "Snowboard Case",
        description: "This is a bag for carrying your snowboard in, all of our snowboards will fit in this bag.",
        price: " 999",
        image: "./products/product_images/snowboardbags/snowboardbag_boardcase.jpg",
        type: "Bag",
        popularity: "0",
    }
]